### ISSUE TITLE
end_lineno error while running python 3.7

### ISSUE THREAD

**Issue by ArcLightSlavik** [snok/pep585-upgrade#15]
Adding hook via:
```
  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: ''
    hooks:
      - id: upgrade-type-hints
        args: [ '--futures=true' ]
```

When running in a python 3.9 virtualenv everything works, but switching to python 3.7 causes this error:

```
Upgrade type hints.......................................................Failed
- hook id: upgrade-type-hints
- exit code: 1

Traceback (most recent call last):
  File "/home/some_name/.cache/pre-commit/repoh9mucjmj/py_env-python3.7/bin/upgrade-type-hints-script", line 8, in <module>
    sys.exit(main())
  File "/home/some_name/.cache/pre-commit/repoh9mucjmj/py_env-python3.7/lib/python3.7/site-packages/src/upgrade_type_hints/main.py", line 33, in main
    annotation_list, imports, futures_import_found = find_annotations_and_imports_in_file(filename)
  File "/home/some_name/.cache/pre-commit/repoh9mucjmj/py_env-python3.7/lib/python3.7/site-packages/src/upgrade_type_hints/checker.py", line 128, in find_annotations_and_imports_in_file
    imports, futures_import_found = map_imports(tree)
  File "/home/some_name/.cache/pre-commit/repoh9mucjmj/py_env-python3.7/lib/python3.7/site-packages/src/upgrade_type_hints/checker.py", line 113, in map_imports
    imports[item.lineno]['end_lineno'] = item.end_lineno
AttributeError: 'Import' object has no attribute 'end_lineno'
Traceback (most recent call last):
  File "/home/some_name/.cache/pre-commit/repoh9mucjmj/py_env-python3.7/bin/upgrade-type-hints-script", line 8, in <module>
    sys.exit(main())
  File "/home/some_name/.cache/pre-commit/repoh9mucjmj/py_env-python3.7/lib/python3.7/site-packages/src/upgrade_type_hints/main.py", line 33, in main
    annotation_list, imports, futures_import_found = find_annotations_and_imports_in_file(filename)
  File "/home/some_name/.cache/pre-commit/repoh9mucjmj/py_env-python3.7/lib/python3.7/site-packages/src/upgrade_type_hints/checker.py", line 128, in find_annotations_and_imports_in_file
    imports, futures_import_found = map_imports(tree)
  File "/home/some_name/.cache/pre-commit/repoh9mucjmj/py_env-python3.7/lib/python3.7/site-packages/src/upgrade_type_hints/checker.py", line 113, in map_imports
    imports[item.lineno]['end_lineno'] = item.end_lineno
AttributeError: 'Import' object has no attribute 'end_lineno'
```

**Comment by sondrelg** [comment]
Thanks for letting me know @ArcLightSlavik 👏

Do you know what specific Python syntax that triggers the error? Are you able to narrow it down to a single file or code snippet?

**Comment by ArcLightSlavik** [comment]
I ran it against https://github.com/ArcLightSlavik/coding, think the issue is that end_lineno was added in python3.8? https://restrictedpython.readthedocs.io/en/latest/contributing/changes_from37to38.html

**Comment by sondrelg** [comment]
That certainly sounds like a plausible explanation 🙂  

Would you be interested in trying to create a fix?

**Comment by ArcLightSlavik** [comment]
I've tried but couldn't really achieve anything :frowning_face: 
The closest solution I've found was: https://stackoverflow.com/a/39879026/12750738, but it had issues with ":" from the "test_map_imports.py" file (which fails under 3.7)

**Comment by sondrelg** [comment]
Well thanks a lot for trying 👏 

I wrote this for a one-time conversion of my own projects where I run python 3.9 myself, so I only really added the 3.7+ stuff so it might benefit others, but not sure it's worth spending a lot of time getting this tuned exactly right. I think I might upgrade the README though, to reflect that 3.7 won't work - thanks again for reporting this🙂 

For your project, you could check out [pyupgrade](https://github.com/asottile/pyupgrade#pep-585-typing-rewrites) as a possible alternative if you haven't already. The only downside to using that is that it doesn't handle `from __futures__ import annotations` imports for you, it doesn't remove unused typing imports after converting types, and it only works for the builtin types - not the collections types that were also introduced in the PEP; but it should do the job 👍

**Comment by ArcLightSlavik** [comment]
Yeah, I just changed to a 3.9 venv and it worked that way 🙂

Should I close this issue or do you prefer to keep this one?

**Comment by sondrelg** [comment]
I changed the readme to say 3.8+ so I guess we're good to close it 🙂 happy to hear it worked!

**Comment by ArcLightSlavik** [comment]
👍 Might want to remove 3.7 from github actions as well
